[package]
name = "yaos"
version = "0.1.0"
authors = ["Maurice Hieronymus <maurice_hieronymus@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
crate-type = ["staticlib"]